### ISSUE TITLE
LK source code for MSM8996 ?

### ISSUE THREAD

**Issue by titusece** [littlekernel/lk#155]
Bootloader source code for MSM8996 (Snapdragon 820) ??

Thanks.

Regards,
Titus S.

**Comment by nvll** [comment]
You'll need to check with Qualcomm. It may be available in their public
repos (some used to be), but due to LK's license they're under no
obligation to release it.

**Comment by M1cha** [comment]
tag LA.HB.1.3.2-23200-8x96.0 from https://www.codeaurora.org/cgit/quic/la/kernel/lk

**Comment by titusece** [comment]
Thank you so much nvll and M1cha.
I appreciate your prompt help.
Thanks again.
