### ISSUE TITLE
source for msm 8930 

### ISSUE THREAD

**Issue by dkm635** [littlekernel/lk#183]
please, give me hint where can i find the same repo for msm8930ab 
thanks.

**Comment by M1cha** [comment]
this repo is for upstream LK and Qualcomm uses an old fork from 2009.
The branch used for msm8930ab is LA.AF.1.1-02810-8064.0: https://source.codeaurora.org/quic/la/kernel/lk/tree/?h=LA.AF.1.1-02810-8064.0

You can compile the msm8960 target which supports your soc.

**Comment by dkm635** [comment]
thanx ,
no need to alter anything to support msm8960 ?

**Comment by dkm635** [comment]
i am not sure about this but 

git clone git://source.codeaurora.org/quic/la/kernel/lk/tree/?h=LA.AF.1.1-02810-8064.0

Cloning into '?h=LA.AF.1.1-02810-8064.0'...

fatal: remote error: access denied or repository not exported: /quic/la/kernel/lk/tree/?h=LA.AF.1.1-02810-8064.0

i dont know how am i supposed to clone or download from that page

**Comment by M1cha** [comment]
git clone https://source.codeaurora.org/quic/la/kernel/lk -b LA.AF.1.1-02810-8064.0
lk uses the same target for all variants of a base soc, that's why the msm8960 should fully support msm8930ab.

**Comment by dkm635** [comment]
i have downloaded it 
are there any libraries or special  compilers  needed to make it ?


-HP-Notebook:/home/dkm/lk# make msm8960
make[1]: Entering directory '/home/dkm/lk'
make[1]: arm-eabi-gcc: Command not found
including app/aboot dev/fbcon dev/keys dev/panel/msm dev/pmic/pm8921 dev/ssbi lib/debug lib/heap lib/libc lib/openssl lib/ptable
including lib/openssl/crypto
generating build-msm8960/config.h
compiling arch/arm/crt0.S
make[1]: arm-eabi-gcc: Command not found
arch/arm/compile.mk:36: recipe for target 'build-msm8960/arch/arm/crt0.o' failed
make[1]: *** [build-msm8960/arch/arm/crt0.o] Error 127
make[1]: Leaving directory '/home/dkm/lk'
makefile:20: recipe for target 'make-make' failed
make: *** [make-make] Error 2

**Comment by M1cha** [comment]
@dkm635 no, just the default stuff like your arm gcc toolchain.

**Comment by dkm635** [comment]
its returning the above error in ubuntu

**Comment by M1cha** [comment]
you have to install an bare-metal ARM toolchain and tell lk the prefix using the TOOLCHAIN_PREFIX environment variable.

If you don't understand that, just google it because it's usual setup stuff that other people have already explained a thousand times.

**Comment by zeusk** [comment]
note that the qualcomm/quic/caf sources are for dev boards so you'll likely have to make quite some changes before you can get it to run on your device. Also, 8930 and 8960 were not so homebrew friendly (first snapdragons with TZ afaik).

**Comment by M1cha** [comment]
@zeusk the changes are usually quite minor but generally you're right. I'm using CAF-LK on tons of production devices and most of the time all you need to change is:
- mmc ports/timings
- lcd driver
- keypad

**Comment by dkm635** [comment]
@zeusk,@m1cha   thanx for your time ,
 after you mentioned about the 8960's trust zone feature  i am more concerned about what i am trying to achieve with all this , 
the discussion might go out of scope of this thread , but i am actually trying to change the bootloader of a device nokia  lumia 1320 which has msm8930ab so that i can have fastboot 
interface (Q.1 is it even possible ) 
and   flash a android rom , 
and as the first step , i need the bootloader  made for my device 
(Q.2 what if i get it from any other device's rom package having msm8930  , will it work )
for which i searched  and found this repo, 
i am willing  to invest my time even so its almost tough level 999999999 for me and qualcomm don't provide data sheets(clocks etc  ) 
(Q.3.do i need it in order to customize the bootloader sources   )
 not only that  , every time i post here it feels as appropriate as poking a stranger in stomach 
what should i do, 
if there is any specific  communtiy that can help me in this case  
please forgive as i am poking you in your stomach

**Comment by dkm635** [comment]
i am just a noob at my best

**Comment by M1cha** [comment]
@feherneoh

**Comment by M1cha** [comment]
@dkm635 afaik there's a Lumia Android slack community but you can also join efidroid since the same people including feherneoh should be there http://join-efidroid.rhcloud.com

**Comment by dkm635** [comment]
thank you sir , i should close this

**Comment by feherneoh** [comment]
@dkm635 if you give me an email address, I can invite you to the Lumia Android slack

**Comment by dkm635** [comment]
dkm635@gmail.com
but think i am in slack already
