### ISSUE TITLE
Snapdragon 820 MSM8996

### ISSUE THREAD

**Issue by umerov1999** [littlekernel/lk#184]
Can I flash lk bootloader for Snapdragon 820 MSM8996 on ZTE Axon 7? This Smartphone using verificate bootloader(Проверяет загрузчик по x509 ключу)

**Comment by M1cha** [comment]
This is not the code, Qualcomm uses for LK, they use: https://www.codeaurora.org/cgit/quic/la/kernel/lk
Also, you usually can't replace the existing LK, because it's signed. You'd have to chainload it from fastboot or from the boot/recovery partition.

**Comment by dhimanchakraborty** [comment]
Is there any document available to build qualcomm little kernel and chainload it from fastboot or from the boot/recovery partition?

**Comment by travisg** [comment]
No, this project is unrelated to the qualcomm bootloader. See previous comments.
