### ISSUE TITLE
nrf52-pca10040-test project seems to be missing platform/gpio.h

### ISSUE THREAD

**Issue by travisg** [littlekernel/lk#271]
While building this project it seems that this particular file is missing. Was it missed in the initial checkin?

compiling target/nrf-pca10040/init.c
target/nrf-pca10040/init.c:13:10: fatal error: platform/gpio.h: No such file or directory

**Comment by hollanderic** [comment]
the nrf52xx platform changes broke this target.  I had forgot the pca10040 used a nrf52 part, thinking it was a nrf51.

Fixed in [38dd509](https://github.com/littlekernel/lk/commit/38dd509b2718c697dfd57632cf03f4ea67897d19)

**Comment by titiavila1983** [comment]
Travis do you think i can get you to put something on my phones where my
husnand can stop taking my messages and phone calls and when i text he vets
it first not the people. Please and soemthing that can protect my fotos. He
moves them all to his phone its crazy
