### ISSUE TITLE
What is PMM/PMM arena?

### ISSUE THREAD

**Issue by lucaszanella** [littlekernel/lk#283]
Hello, I have a simple question. What PMM stands for? What is a PMM arena? Can't find any of these concepts on google.

Thanks!

**Comment by travisg** [comment]
Ah, the PMM is the 'physical memory manager'. In a system where there's a
paging memory management unit (MMU) it is the part the tracks the allocated
and free physical memory pages. The VMM is the virtual memory manager, and
it allocates and frees pages from the PMM.

A PMM Arena is a single run of physical memory. Say on a computer with 2GB
ram it may be from address 0 to 0x80000000. There may be more than one
arena if physical memory is chopped into multiple chunks, which is fairly
common on PCs at least.
