### ISSUE TITLE
[bug][arm64] add way/set cache flush routines for arm64

### ISSUE THREAD

**Issue by cleverca22** [littlekernel/lk#307]
i was implementing `arch_chain_load()` for arm64 this week, and the only major blocker ive run into and cant solve easily, is that `arch_disable_cache()` is also not implemented on arm64

checking the armv8 docs, `DC CISW, Data or unified Cache line Clean and Invalidate by Set/Way` appears to be the best opcode

**Comment by travisg** [comment]
Okay, should have implemented this. No test case currently implemented, but I know the place it was pulled from it's well tested.
