### ISSUE TITLE
[Feature] Dual boot support

### ISSUE THREAD

**Issue by GreenLunar** [littlekernel/lk#363]
Add a feature to choose which install to boot each time a device turns on or allowing some kind of configuration for changing which install is preferred on boot.

Source https://github.com/msm8916-mainline/lk2nd/issues/100

**Comment by luka177** [comment]
are you kidding? Even single-booting is out of the scope of this project, this project is just kernel, not bootloader. Qcom platforms did use OLD and MODED lk to boot linux + even for it there is dualboot solution, check https://github.com/Android-Boot-Manager

**Comment by luka177** [comment]
Issue should be closed now

**Comment by GreenLunar** [comment]
Thank you for the reference.

I'll look into it.

P.S. I'm attempting to dual boot multiple pure Linux OSs.

**Comment by travisg** [comment]
Unfortunately luka177 is right. The Qualcomm bootloader you're probably referring to is a really really old fork of LK (like 2009 era) that has diverged from mainline in a ton of ways. I honestly don't know what it's doing with any of these things, so you'd really have to start with that codebase and work from there.
